# Header
menu:
  首页: /
  所有文章: /archives
rss: /atom.xml

# Content
excerpt_link: 查看更多
fancybox: true
livere: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archives
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics: UA-132214073-1
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus: 113053451579323203207
fb_admins:
fb_app_id:
