name: Hexo Generate

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the hexo branch
on:
  push:
    branches: [ hexo ]
  pull_request:
    branches: [ hexo ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      
      # Sets up cache 
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      # Installs Node.js and its dependencies 
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install Hexo-cli
        run: npm install -g hexo-cli
        
      - name: Install hexo and its plugins
        run: |
          npm ci
          npm install hexo-deployer-git --save
          npm uninstall hexo-generator-index --save
          npm install hexo-generator-index-pin-top --save
          
      - name: Hexo generate
        run: |
          hexo clean
          hexo generate
          
      # Post-generation steps (Updating pages)        
      - name: Set up git
        run: |
          git config user.name "mgrddsj"
          git config user.email "Jesse_Xu@live.com"

      - name: Check out the pages repo
        uses: actions/checkout@v2
        with:
              repository: 'mgrddsj/mgrddsj.github.io'
              ref: 'master'
              path: '.deploy_git'

      - name: modifies the pages repo
        run: |
          find ./.deploy_git -path ./.git -prune -o -exec rm -rf {} \; 2> /dev/null
      
      - name: Deploy files to pages
        env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
          hexo deploy